### ISSUE TITLE
Allow changing severity of flake8 messages

### ISSUE THREAD

**Issue by nawordar** [palantir/python-language-server#953]
It annoys me that all pyflakes messages reported by flake8 have severity of errors. I know this is subjective and some people prefer to have everything reported as errors, so I think this should be configurable. For example:

```yaml
{
  "pyls.plugins.flake8.severity": {
    "F": "warning",  # Set default severity of pyflakes messages to warning
    "F999": "error"  # ...but display F999 messages as errors
  }
}
```
